import os
import re
from datetime import datetime
from fpdf import FPDF


def sanitize_for_pdf(text: str) -> str:
    """Strip emojis and non-latin1 characters that break standard PDF fonts."""
    if not isinstance(text, str):
        text = str(text)
    # Remove emoji and unicode symbols
    clean = re.sub(r'[^\x00-\xFF]', '', text)
    # Clean up any leftover awkward spacing
    return clean.strip()


def generate_markdown_report(ioc: str, ioc_type: str, results: list, score_data: dict) -> str:
    """Generate a Markdown triage report"""
    from modules.score_engine import get_recommendation

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    severity = score_data["severity"]
    recommendation = get_recommendation(severity)

    md = f"""# 🔍 Threat Intelligence Triage Report

---

## Executive Summary

| Field | Value |
|-------|-------|
| **IOC** | `{ioc}` |
| **Type** | {ioc_type.upper()} |
| **Final Threat Score** | **{score_data['final_score']}/100** |
| **Severity** | **{severity}** |
| **Timestamp** | {timestamp} |
| **Analyst Tool** | SOAR-Lite Automated Triage |

---

## Recommendation

{recommendation}

---

## Score Breakdown

| Source | Raw Score | Weight | Weighted Contribution |
|--------|-----------|--------|-----------------------|
"""

    for source, details in score_data.get("breakdown", {}).items():
        md += f"| {source.title()} | {details['raw_score']} | {details['weight']} | {details['weighted_contribution']} |\n"

    if score_data.get("skipped_sources"):
        md += f"\n**Skipped Sources:** {', '.join(score_data['skipped_sources'])}\n"

    md += "\n---\n\n## Detailed Source Results\n\n"

    for result in results:
        md += f"### {result.get('source', 'Unknown')}\n\n"
        if result.get("error"):
            md += f"⚠️ **Error:** {result['error']}\n\n"
        else:
            md += "| Field | Value |\n|-------|-------|\n"
            for key, value in result.items():
                if key not in ["source", "error", "skipped"]:
                    md += f"| {key} | {value} |\n"
            md += "\n"

    md += f"""---

## MITRE ATT&CK Mapping Suggestions

Based on the IOC type `{ioc_type}`:
"""

    if ioc_type == "ip":
        md += """
- **T1071** - Application Layer Protocol (C2 communication)
- **T1090** - Proxy (Traffic routing through malicious infrastructure)
- **T1041** - Exfiltration Over C2 Channel
"""
    elif ioc_type == "domain":
        md += """
- **T1071.001** - Web Protocols (Malicious domain for C2)
- **T1568** - Dynamic Resolution (DGA domains)
- **T1566** - Phishing (Malicious link delivery)
"""
    elif ioc_type == "hash":
        md += """
- **T1204** - User Execution (Malware execution)
- **T1059** - Command and Scripting Interpreter
- **T1105** - Ingress Tool Transfer
"""

    md += f"\n---\n\n*Report generated by SOAR-Lite Threat Intel Tool | {timestamp}*\n"

    os.makedirs("reports", exist_ok=True)
    filename = f"reports/triage_{ioc.replace('.', '_').replace(':', '_')}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(md)

    return filename


def generate_pdf_report(ioc: str, ioc_type: str, results: list, score_data: dict) -> str:
    """Generate a sanitized PDF triage report"""
    from modules.score_engine import get_recommendation

    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    filename = f"reports/triage_{ioc.replace('.', '_').replace(':', '_')}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(33, 37, 41)
    pdf.cell(0, 12, "Threat Intelligence Triage Report", ln=True, align="C")
    pdf.ln(4)

    # Horizontal divider rule
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Executive Summary Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 8, "Executive Summary", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 6, f"Target IOC: {sanitize_for_pdf(ioc)}", ln=True)
    pdf.cell(0, 6, f"IOC Type: {sanitize_for_pdf(ioc_type.upper())}", ln=True)
    pdf.cell(0, 6, f"Overall Threat Score: {score_data['final_score']} / 100", ln=True)
    pdf.cell(0, 6, f"Severity Classification: {sanitize_for_pdf(score_data['severity'])}", ln=True)
    pdf.cell(0, 6, f"Generated At: {timestamp}", ln=True)
    pdf.ln(4)

    # Actionable Recommendation Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 8, "Analyst Action Recommendation", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    recommendation = get_recommendation(score_data["severity"])
    pdf.multi_cell(0, 6, sanitize_for_pdf(recommendation))
    pdf.ln(4)

    # Score Breakdown Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 8, "Scoring Breakdown by Source", ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)
    for source, details in score_data.get("breakdown", {}).items():
        line = f"- {source.upper()}: Raw Score = {details['raw_score']}, Weight = {details['weight']}, Weighted Contribution = {details['weighted_contribution']}"
        pdf.cell(0, 5, sanitize_for_pdf(line), ln=True)
    pdf.ln(4)

    # Detailed Results Section
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 102, 204)
    pdf.cell(0, 8, "OSINT Source Findings", ln=True)

    for result in results:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        source_name = sanitize_for_pdf(result.get("source", "Unknown"))
        pdf.cell(0, 7, f"Source: {source_name}", ln=True)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        if result.get("error"):
            pdf.cell(0, 5, f"  Status: Error - {sanitize_for_pdf(result['error'])}", ln=True)
        else:
            for key, value in result.items():
                if key not in ["source", "error", "skipped"]:
                    clean_k = sanitize_for_pdf(str(key))
                    clean_v = sanitize_for_pdf(str(value))
                    pdf.cell(0, 5, f"  {clean_k}: {clean_v}", ln=True)
        pdf.ln(2)

    pdf.output(filename)
    return filename
